// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stock.Data;

#nullable disable

namespace Stock.Migrations
{
    [DbContext(typeof(StockDbContext))]
    [Migration("20260629041201_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Stock.Data.CorpActionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BcEndDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BcStartDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaBroadcastDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaceVal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ind")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NdEndDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NdStartDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CorpActions");
                });

            modelBuilder.Entity("Stock.Data.CorpAnnualReportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttFileSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BroadcastDttm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisseminationDateTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromYr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubmissionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeTaken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToYr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CorpAnnualReports");
                });

            modelBuilder.Entity("Stock.Data.CorpBoardMeetingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttFileSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Attachment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BmDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BmDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BmPurpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BmSymbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BmTimestamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diff")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ixbrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IxbrlFileSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmIndustry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmIsin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SysTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CorpBoardMeetings");
                });

            modelBuilder.Entity("Stock.Data.CorpEventCalendarEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BmAnSeqId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BmAttachment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BmDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BmDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BmDt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BmPurpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BmSymbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BmTimestamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BmTimestampFull")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmIndustry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmIsin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CorpEventCalendars");
                });

            modelBuilder.Entity("Stock.Data.CorporateAnnouncementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnDt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttFileSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttchmntFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttchmntText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bflag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CsvName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Difference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExchDissTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasXbrl")
                        .HasColumnType("bit");

                    b.Property<string>("OldNew")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Orgid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeqId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmIndustry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmIsin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SortDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CorporateAnnouncements");
                });

            modelBuilder.Entity("Stock.Data.EquityListingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfListing")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FaceValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ISINNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MarketLot")
                        .HasColumnType("int");

                    b.Property<string>("NameOfCompany")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PaidUpValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EquityListings");
                });

            modelBuilder.Entity("Stock.Data.EquitySymbolDataEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastUpdateTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MetaDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OrderBookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PriceInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SecInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SymbolDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TradeInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MetaDataId");

                    b.HasIndex("OrderBookId");

                    b.HasIndex("PriceInfoId");

                    b.HasIndex("SecInfoId");

                    b.HasIndex("SymbolDataId");

                    b.HasIndex("TradeInfoId");

                    b.ToTable("EquitySymbolDataEntities");
                });

            modelBuilder.Entity("Stock.Data.FinancialStatusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Audited")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Consolidated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cumulative")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Eps")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Expenditure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("NetProLossAftTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReBroadcastTimestamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ReProLossBefTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Series")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToDateMonYr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalIncome")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("FinancialStatuses");
                });

            modelBuilder.Entity("Stock.Data.HistoricalTradeDataEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FromDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Ch52WeekHighPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Ch52WeekLowPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ChClosingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ChLastTradedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ChOpeningPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ChPreviousClsPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ChSeries")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ChTotTradedQty")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ChTotTradedVal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ChTotalTrades")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ChTradeHighPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ChTradeLowPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MTimestamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Vwap")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("HistoricalTradeDataEntities");
                });

            modelBuilder.Entity("Stock.Data.IndexDataEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConstituentsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("High")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IcChange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IcPerChange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IndexName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("IndicativeClose")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IsConstituents")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Last")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Low")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Open")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PercChange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PreviousClose")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TimeVal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("YearHigh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("YearLow")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("IndexDataEntities");
                });

            modelBuilder.Entity("Stock.Data.IndicesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Advances")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChartTodayPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DY")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Declines")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("High")
                        .HasColumnType("float");

                    b.Property<string>("Index")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndexSymbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Last")
                        .HasColumnType("float");

                    b.Property<double>("Low")
                        .HasColumnType("float");

                    b.Property<double>("Open")
                        .HasColumnType("float");

                    b.Property<string>("PB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PerChange30d")
                        .HasColumnType("float");

                    b.Property<double>("PerChange365d")
                        .HasColumnType("float");

                    b.Property<double>("PercentChange")
                        .HasColumnType("float");

                    b.Property<double>("PreviousClose")
                        .HasColumnType("float");

                    b.Property<string>("Unchanged")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Variation")
                        .HasColumnType("float");

                    b.Property<double>("YearHigh")
                        .HasColumnType("float");

                    b.Property<double>("YearLow")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Indices");
                });

            modelBuilder.Entity("Stock.Data.MetaDataEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AdjPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AveragePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Change")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ClosePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DayHigh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DayLow")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IcChange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IcPchange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Iep")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Ieq")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IndicativeClose")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IsinCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarketType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Open")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PChange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PreviousClose")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SpoChange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SpoPchange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SymbolStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MetaDataEntities");
                });

            modelBuilder.Entity("Stock.Data.OrderBookEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BuyPrice1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BuyPrice2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BuyPrice3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BuyPrice4")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BuyPrice5")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("BuyQuantity1")
                        .HasColumnType("bigint");

                    b.Property<long>("BuyQuantity2")
                        .HasColumnType("bigint");

                    b.Property<long>("BuyQuantity3")
                        .HasColumnType("bigint");

                    b.Property<long>("BuyQuantity4")
                        .HasColumnType("bigint");

                    b.Property<long>("BuyQuantity5")
                        .HasColumnType("bigint");

                    b.Property<decimal>("LastPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PerBuyQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PerSellQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SellPrice1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SellPrice2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SellPrice3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SellPrice4")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SellPrice5")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("SellQuantity1")
                        .HasColumnType("bigint");

                    b.Property<long>("SellQuantity2")
                        .HasColumnType("bigint");

                    b.Property<long>("SellQuantity3")
                        .HasColumnType("bigint");

                    b.Property<long>("SellQuantity4")
                        .HasColumnType("bigint");

                    b.Property<long>("SellQuantity5")
                        .HasColumnType("bigint");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TotalBuyQuantity")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalSellQuantity")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("OrderBookEntities");
                });

            modelBuilder.Entity("Stock.Data.PeerComparisonDataEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("DebtEqRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Eps")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Ltp")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MarketCap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MarketType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PChange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PChangeUpper")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Pat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Pe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PromoterHolding")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("PeerComparisonDataEntities");
                });

            modelBuilder.Entity("Stock.Data.PriceInfoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CmAnnualVolatility")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CmDailyVolatility")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Inav")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IsINav")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PPriceBand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriceBand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TickSize")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("YearHigh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("YearHighDt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("YearLow")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("YearLowDt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PriceInfoEntities");
                });

            modelBuilder.Entity("Stock.Data.SecInfoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdhocMargin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicableMargin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BasicIndustry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BoardStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BondType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassShare")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CouponRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditRating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryQuantity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryTotradedQuantity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtremeLossMargin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Index")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndexListJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndexVar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndustryInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsSuspended")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssueDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssueDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListingDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Macro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaturityDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfComplianceOfficer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NxtIpDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdSectorInd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PdSectorPe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PdSymbolPe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SddCompliance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityVar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TradingSegment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VarMargin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SecInfoEntities");
                });

            modelBuilder.Entity("Stock.Data.ShareholdingPatternEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ndsid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ShareholdingPatternEntries");
                });

            modelBuilder.Entity("Stock.Data.SymbolDataEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MarketType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SymbolDataEntities");
                });

            modelBuilder.Entity("Stock.Data.TradeInfoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ApplicableMargin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("DeliveryQuantity")
                        .HasColumnType("bigint");

                    b.Property<decimal>("DeliveryToTradedQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FaceValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Ffmc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ImpactCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("IssuedSize")
                        .HasColumnType("bigint");

                    b.Property<decimal>("LastPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MarketLot")
                        .HasColumnType("int");

                    b.Property<long>("QuantityTraded")
                        .HasColumnType("bigint");

                    b.Property<string>("SecWiseDelPosDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalMarketCap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalTradedValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("TotalTradedVolume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("TradeInfoEntities");
                });

            modelBuilder.Entity("Stock.Data.YearwiseDataEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("FiveYearChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IndexFiveYearChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IndexName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("IndexOneMonthChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IndexOneWeekChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IndexOneWeekDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("IndexOneYearChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IndexSixMonthChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IndexThreeMonthChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IndexThreeYearChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IndexTwoYearChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IndexYesterdayChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OneMonthChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OneWeekChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OneWeekDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OneYearChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SixMonthChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ThreeMonthChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ThreeYearChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TwoYearChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("YesterdayChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("YearwiseDataEntities");
                });

            modelBuilder.Entity("Stock.Data.EquitySymbolDataEntity", b =>
                {
                    b.HasOne("Stock.Data.MetaDataEntity", "MetaData")
                        .WithMany()
                        .HasForeignKey("MetaDataId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stock.Data.OrderBookEntity", "OrderBook")
                        .WithMany()
                        .HasForeignKey("OrderBookId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stock.Data.PriceInfoEntity", "PriceInfo")
                        .WithMany()
                        .HasForeignKey("PriceInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stock.Data.SecInfoEntity", "SecInfo")
                        .WithMany()
                        .HasForeignKey("SecInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stock.Data.SymbolDataEntity", "SymbolData")
                        .WithMany("EquityResponse")
                        .HasForeignKey("SymbolDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Stock.Data.TradeInfoEntity", "TradeInfo")
                        .WithMany()
                        .HasForeignKey("TradeInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("MetaData");

                    b.Navigation("OrderBook");

                    b.Navigation("PriceInfo");

                    b.Navigation("SecInfo");

                    b.Navigation("SymbolData");

                    b.Navigation("TradeInfo");
                });

            modelBuilder.Entity("Stock.Data.SymbolDataEntity", b =>
                {
                    b.Navigation("EquityResponse");
                });
#pragma warning restore 612, 618
        }
    }
}
