// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stock.Entity;

#nullable disable

namespace Stock.Migrations
{
    [DbContext(typeof(StockDbContext))]
    partial class StockDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Stock.Entity.AiRecommendationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol");

                    b.ToTable("AiRecommendations");
                });

            modelBuilder.Entity("Stock.Entity.EquityListingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfListing")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FaceValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ISINNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MarketLot")
                        .HasColumnType("int");

                    b.Property<string>("NameOfCompany")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PaidUpValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EquityListings");
                });

            modelBuilder.Entity("Stock.Entity.FavoriteSymbolEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FavoriteSymbolEntities");
                });

            modelBuilder.Entity("Stock.Entity.MetaDataEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AdjPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AveragePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Change")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ClosePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DayHigh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DayLow")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IcChange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IcPchange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Iep")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Ieq")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IndicativeClose")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IsinCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarketType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Open")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PChange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PreviousClose")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SpoChange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SpoPchange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SymbolStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("MetaDataEntities");
                });

            modelBuilder.Entity("Stock.Entity.OrderBookEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BuyPrice1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BuyPrice2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BuyPrice3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BuyPrice4")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BuyPrice5")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("BuyQuantity1")
                        .HasColumnType("bigint");

                    b.Property<long>("BuyQuantity2")
                        .HasColumnType("bigint");

                    b.Property<long>("BuyQuantity3")
                        .HasColumnType("bigint");

                    b.Property<long>("BuyQuantity4")
                        .HasColumnType("bigint");

                    b.Property<long>("BuyQuantity5")
                        .HasColumnType("bigint");

                    b.Property<decimal>("LastPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PerBuyQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PerSellQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SellPrice1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SellPrice2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SellPrice3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SellPrice4")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SellPrice5")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("SellQuantity1")
                        .HasColumnType("bigint");

                    b.Property<long>("SellQuantity2")
                        .HasColumnType("bigint");

                    b.Property<long>("SellQuantity3")
                        .HasColumnType("bigint");

                    b.Property<long>("SellQuantity4")
                        .HasColumnType("bigint");

                    b.Property<long>("SellQuantity5")
                        .HasColumnType("bigint");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("TotalBuyQuantity")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalSellQuantity")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("OrderBookEntities");
                });

            modelBuilder.Entity("Stock.Entity.PriceInfoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CmAnnualVolatility")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CmDailyVolatility")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Inav")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IsINav")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PPriceBand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PriceBand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("TickSize")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("YearHigh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("YearHighDt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("YearLow")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("YearLowDt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("PriceInfoEntities");
                });

            modelBuilder.Entity("Stock.Entity.SecInfoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdhocMargin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicableMargin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BasicIndustry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BoardStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BondType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassShare")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CouponRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditRating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryQuantity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryTotradedQuantity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtremeLossMargin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Index")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndexList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IndexListJson");

                    b.Property<string>("IndexVar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndustryInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsSuspended")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssueDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssueDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListingDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Macro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaturityDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfComplianceOfficer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NxtIpDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdSectorInd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PdSectorPe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PdSymbolPe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SddCompliance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityVar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TradingSegment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VarMargin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("SecInfoEntities");
                });

            modelBuilder.Entity("Stock.Entity.SymbolDataEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MarketType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("SymbolDataEntities");
                });

            modelBuilder.Entity("Stock.Entity.TradeInfoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ApplicableMargin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("DeliveryQuantity")
                        .HasColumnType("bigint");

                    b.Property<decimal>("DeliveryToTradedQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FaceValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Ffmc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ImpactCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("IssuedSize")
                        .HasColumnType("bigint");

                    b.Property<decimal>("LastPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MarketLot")
                        .HasColumnType("int");

                    b.Property<long>("QuantityTraded")
                        .HasColumnType("bigint");

                    b.Property<string>("SecWiseDelPosDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("TotalMarketCap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalTradedValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("TotalTradedVolume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("TradeInfoEntities");
                });

            modelBuilder.Entity("Stock.Entity.YearwiseDataEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("FiveYearChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IndexFiveYearChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IndexName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("IndexOneMonthChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IndexOneWeekChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IndexOneWeekDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("IndexOneYearChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IndexSixMonthChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IndexThreeMonthChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IndexThreeYearChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IndexTwoYearChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IndexYesterdayChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OneMonthChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OneWeekChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OneWeekDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OneYearChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SixMonthChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ThreeMonthChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ThreeYearChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TwoYearChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("YesterdayChangePercent")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("YearwiseDataEntities");
                });

            modelBuilder.Entity("Stock.Entity.AiRecommendationEntity", b =>
                {
                    b.HasOne("Stock.Entity.MetaDataEntity", "MetaData")
                        .WithMany()
                        .HasForeignKey("Symbol")
                        .HasPrincipalKey("Symbol")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Stock.Entity.SecInfoEntity", "SecInfo")
                        .WithMany()
                        .HasForeignKey("Symbol")
                        .HasPrincipalKey("Symbol")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MetaData");

                    b.Navigation("SecInfo");
                });

            modelBuilder.Entity("Stock.Entity.MetaDataEntity", b =>
                {
                    b.HasOne("Stock.Entity.SymbolDataEntity", null)
                        .WithOne("MetaData")
                        .HasForeignKey("Stock.Entity.MetaDataEntity", "Symbol")
                        .HasPrincipalKey("Stock.Entity.SymbolDataEntity", "Symbol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stock.Entity.OrderBookEntity", b =>
                {
                    b.HasOne("Stock.Entity.SymbolDataEntity", null)
                        .WithOne("OrderBook")
                        .HasForeignKey("Stock.Entity.OrderBookEntity", "Symbol")
                        .HasPrincipalKey("Stock.Entity.SymbolDataEntity", "Symbol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stock.Entity.PriceInfoEntity", b =>
                {
                    b.HasOne("Stock.Entity.SymbolDataEntity", null)
                        .WithOne("PriceInfo")
                        .HasForeignKey("Stock.Entity.PriceInfoEntity", "Symbol")
                        .HasPrincipalKey("Stock.Entity.SymbolDataEntity", "Symbol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stock.Entity.SecInfoEntity", b =>
                {
                    b.HasOne("Stock.Entity.SymbolDataEntity", null)
                        .WithOne("SecInfo")
                        .HasForeignKey("Stock.Entity.SecInfoEntity", "Symbol")
                        .HasPrincipalKey("Stock.Entity.SymbolDataEntity", "Symbol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stock.Entity.TradeInfoEntity", b =>
                {
                    b.HasOne("Stock.Entity.SymbolDataEntity", null)
                        .WithOne("TradeInfo")
                        .HasForeignKey("Stock.Entity.TradeInfoEntity", "Symbol")
                        .HasPrincipalKey("Stock.Entity.SymbolDataEntity", "Symbol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stock.Entity.SymbolDataEntity", b =>
                {
                    b.Navigation("MetaData");

                    b.Navigation("OrderBook");

                    b.Navigation("PriceInfo");

                    b.Navigation("SecInfo");

                    b.Navigation("TradeInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
