import type { ColDef } from '@ag-grid-community/core';
import { FORMATTERS, FormatterType } from './Columnformatters';

const COLUMN_DEFS: Array<ColDef & { formatter?: FormatterType }> = [
  {
    field: 'companyName',
    headerName: 'Company',
    tooltipField: 'companyName',
    valueFormatter: (params: any) => FORMATTERS.text(params.value),
    sortable: true,
    filter: true,
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 120,
  },
  {
    field: 'sector',
    headerName: 'Sector',
    tooltipField: 'companyName',
    valueFormatter: (params: any) => FORMATTERS.text(params.value),
    sortable: true,
    filter: true,
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 110,
  },
  {
    field: 'basicIndustry',
    headerName: 'Industry',
    pinned: 'left',
    tooltipField: 'companyName',
    valueFormatter: (params: any) => FORMATTERS.text(params.value),
    sortable: true,
    filter: true,
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 140,
  },
  {
    field: 'industryInfo',
    headerName: 'Industry Info',
    tooltipField: 'companyName',
    valueFormatter: (params: any) => FORMATTERS.text(params.value),
    sortable: true,
    filter: true,
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 160,
  },
  {
    field: 'macro',
    headerName: 'Macro',
    tooltipField: 'companyName',
    valueFormatter: (params: any) => FORMATTERS.text(params.value),
    sortable: true,
    filter: true,
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 120,
  },
  {
    field: 'indexName',
    headerName: 'Index',
    tooltipField: 'companyName',
    valueFormatter: (params: any) => FORMATTERS.text(params.value),
    sortable: true,
    filter: true,
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 120,
  },
  {
    field: 'totalTradedVolume',
    headerName: 'Volume',
    tooltipField: 'companyName',
    valueFormatter: (params: any) => FORMATTERS.number(params.value),
    wrapHeaderText: true,
    autoHeaderHeight: true,
    width: 100,
  },
  {
    field: 'totalTradedValue',
    headerName: 'Turnover',
    tooltipField: 'companyName',
    valueFormatter: (params: any) => FORMATTERS.currency(params.value),
    wrapHeaderText: true,
    autoHeaderHeight: true,
    width: 140,
  },
  {
    field: 'quantityTraded',
    headerName: 'Qty Traded',
    tooltipField: 'companyName',
    valueFormatter: (params: any) => FORMATTERS.number(params.value),
    wrapHeaderText: true,
    autoHeaderHeight: true,
    width: 100,
  },
  {
    field: 'deliveryQuantity',
    headerName: 'Delivery Qty',
    tooltipField: 'companyName',
    valueFormatter: (params: any) => FORMATTERS.number(params.value),
    wrapHeaderText: true,
    autoHeaderHeight: true,
    width: 100,
  },
  {
    field: 'totalMarketCap',
    headerName: 'Market Cap',
    tooltipField: 'companyName',
    valueFormatter: (params: any) => FORMATTERS.currency(params.value),
    wrapHeaderText: true,
    autoHeaderHeight: true,
    width: 170,
  },
  {
    field: 'yesterdayChangePercent',
    headerName: 'One Day',
    tooltipField: 'companyName',
    valueFormatter: (params: any) => FORMATTERS.percent(params.value),
    wrapHeaderText: true,
    autoHeaderHeight: true,
    width: 95,
  },
  {
    field: 'oneWeekChangePercent',
    headerName: 'One Week',
    tooltipField: 'companyName',
    valueFormatter: (params: any) => FORMATTERS.percent(params.value),
    wrapHeaderText: true,
    autoHeaderHeight: true,
    width: 85,
  },
  {
    field: 'oneMonthChangePercent',
    headerName: 'One Month',
    tooltipField: 'companyName',
    valueFormatter: (params: any) => FORMATTERS.percent(params.value),
    wrapHeaderText: true,
    autoHeaderHeight: true,
    width: 85,
  },
  {
    field: 'threeMonthChangePercent',
    headerName: 'Three Month',
    tooltipField: 'companyName',
    valueFormatter: (params: any) => FORMATTERS.percent(params.value),
    wrapHeaderText: true,
    autoHeaderHeight: true,
    width: 85,
  },
  {
    field: 'sixMonthChangePercent',
    headerName: 'Six Month',
    tooltipField: 'companyName',
    valueFormatter: (params: any) => FORMATTERS.percent(params.value),
    wrapHeaderText: true,
    autoHeaderHeight: true,
    width: 85,
  },
  {
    field: 'oneYearChangePercent',
    headerName: 'One Year',
    tooltipField: 'companyName',
    valueFormatter: (params: any) => FORMATTERS.percent(params.value),
    wrapHeaderText: true,
    autoHeaderHeight: true,
    width: 95,
  },
  {
    field: 'twoYearChangePercent',
    headerName: 'Two Year',
    tooltipField: 'companyName',
    valueFormatter: (params: any) => FORMATTERS.percent(params.value),
    wrapHeaderText: true,
    autoHeaderHeight: true,
    width: 85,
  },
  {
    field: 'threeYearChangePercent',
    headerName: 'Three Year',
    tooltipField: 'companyName',
    valueFormatter: (params: any) => FORMATTERS.percent(params.value),
    wrapHeaderText: true,
    autoHeaderHeight: true,
    width: 85,
  },
  {
    field: 'fiveYearChangePercent',
    headerName: 'Five Year',
    tooltipField: 'companyName',
    valueFormatter: (params: any) => FORMATTERS.percent(params.value),
    wrapHeaderText: true,
    autoHeaderHeight: true,
    width: 95,
  },
  {
    field: 'indexYesterdayChangePercent',
    headerName: 'Index One Day',
    tooltipField: 'companyName',
    valueFormatter: (params: any) => FORMATTERS.percent(params.value),
    wrapHeaderText: true,
    autoHeaderHeight: true,
    width: 85,
  },
  {
    field: 'indexOneWeekChangePercent',
    headerName: 'Index One Week',
    tooltipField: 'companyName',
    valueFormatter: (params: any) => FORMATTERS.percent(params.value),
    wrapHeaderText: true,
    autoHeaderHeight: true,
    width: 85,
  },
  {
    field: 'indexOneMonthChangePercent',
    headerName: 'Index One Month',
    tooltipField: 'companyName',
    valueFormatter: (params: any) => FORMATTERS.percent(params.value),
    wrapHeaderText: true,
    autoHeaderHeight: true,
    width: 85,
  },
  {
    field: 'indexThreeMonthChangePercent',
    headerName: 'Index Three Month',
    tooltipField: 'companyName',
    valueFormatter: (params: any) => FORMATTERS.percent(params.value),
    wrapHeaderText: true,
    autoHeaderHeight: true,
    width: 85,
  },
  {
    field: 'indexSixMonthChangePercent',
    headerName: 'Index Six Month',
    tooltipField: 'companyName',
    valueFormatter: (params: any) => FORMATTERS.percent(params.value),
    wrapHeaderText: true,
    autoHeaderHeight: true,
    width: 85,
  },
  {
    field: 'indexOneYearChangePercent',
    headerName: 'Index One Year',
    tooltipField: 'companyName',
    valueFormatter: (params: any) => FORMATTERS.percent(params.value),
    wrapHeaderText: true,
    autoHeaderHeight: true,
    width: 85,
  },
  {
    field: 'indexTwoYearChangePercent',
    headerName: 'Index Two Year',
    tooltipField: 'companyName',
    valueFormatter: (params: any) => FORMATTERS.percent(params.value),
    wrapHeaderText: true,
    autoHeaderHeight: true,
    width: 85,
  },
  {
    field: 'indexThreeYearChangePercent',
    headerName: 'Index Three Year',
    tooltipField: 'companyName',
    valueFormatter: (params: any) => FORMATTERS.percent(params.value),
    wrapHeaderText: true,
    autoHeaderHeight: true,
    width: 85,
  },
  {
    field: 'indexFiveYearChangePercent',
    headerName: 'Index Five Year',
    tooltipField: 'companyName',
    valueFormatter: (params: any) => FORMATTERS.percent(params.value),
    wrapHeaderText: true,
    autoHeaderHeight: true,
    width: 95,
  },
];

export const YEARWISE_COLUMNS: ColDef[] = COLUMN_DEFS;