import type { ColDef } from '@ag-grid-community/core';

const COLUMN_DEFS: Array<ColDef> = [
  {
    field: 'macro',
    headerName: 'Macro',
    tooltipField: 'macro',
    sortable: true,
    filter: 'agTextColumnFilter',
    filterParams: { buttons: ['reset', 'apply'], closeOnApply: true },
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 120,
  },
  {
    field: 'indexName',
    headerName: 'Index',
    tooltipField: 'indexName',
    sortable: true,
    filter: 'agSetColumnFilter',
    filterParams: { buttons: ['reset', 'apply'], closeOnApply: true },
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 120,
  },
  {
    field: 'industryInfo',
    headerName: 'Industry Info',
    tooltipField: 'industryInfo',
    sortable: true,
    filter: 'agTextColumnFilter',
    filterParams: { buttons: ['reset', 'apply'], closeOnApply: true },
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 160,
  },
  {
    field: 'basicIndustry',
    headerName: 'Industry',
    pinned: 'left',
    tooltipField: 'basicIndustry',
    sortable: true,
    filter: 'agTextColumnFilter',
    filterParams: { buttons: ['reset', 'apply'], closeOnApply: true },
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 160,
  },
  {
    field: 'sector',
    headerName: 'Sector',
    tooltipField: 'sector',
    sortable: true,
    filter: 'agTextColumnFilter',
    filterParams: { buttons: ['reset', 'apply'], closeOnApply: true },
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 200,
  },
  {
    field: 'companyName',
    headerName: 'Company',
    tooltipField: 'companyName',
    sortable: true,
    filter: 'agTextColumnFilter',
    filterParams: { buttons: ['reset', 'apply'], closeOnApply: true },
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 300,
  },
  // ── Price Columns ─────────────────────────────────────────
  {
    field: 'open',
    headerName: 'Open',
    tooltipField: 'open',
    filter: 'agNumberColumnFilter',
    filterParams: { buttons: ['reset', 'apply'], closeOnApply: true },
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 80,
  },
  {
    field: 'dayHigh',
    headerName: 'Day High',
    tooltipField: 'dayHigh',
    filter: 'agNumberColumnFilter',
    filterParams: { buttons: ['reset', 'apply'], closeOnApply: true },
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 80,
  },
  {
    field: 'dayLow',
    headerName: 'Day Low',
    tooltipField: 'dayLow',
    filter: 'agNumberColumnFilter',
    filterParams: { buttons: ['reset', 'apply'], closeOnApply: true },
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 80,
  },
  {
    field: 'previousClose',
    headerName: 'Prev. Close',
    tooltipField: 'previousClose',
    filter: 'agNumberColumnFilter',
    filterParams: { buttons: ['reset', 'apply'], closeOnApply: true },
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 80,
  },
  {
    field: 'closePrice',
    headerName: 'Close',
    tooltipField: 'closePrice',
    filter: 'agNumberColumnFilter',
    filterParams: { buttons: ['reset', 'apply'], closeOnApply: true },
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 80,
  },
  {
    field: 'yearHigh',
    headerName: '52W High',
    tooltipField: 'yearHigh',
    filter: 'agNumberColumnFilter',
    filterParams: { buttons: ['reset', 'apply'], closeOnApply: true },
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 80,
  },
  {
    field: 'yearLow',
    headerName: '52W Low',
    tooltipField: 'yearLow',
    filter: 'agNumberColumnFilter',
    filterParams: { buttons: ['reset', 'apply'], closeOnApply: true },
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 80,
  },
  // ── Volume / Value Columns ────────────────────────────────
  {
    field: 'totalMarketCap',
    headerName: 'Market Cap',
    tooltipField: 'totalMarketCap',
    filter: 'agNumberColumnFilter',
    filterParams: { buttons: ['reset', 'apply'], closeOnApply: true },
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 150,
  },
  {
    field: 'totalTradedVolume',
    headerName: 'Volume',
    tooltipField: 'totalTradedVolume',
    filter: 'agNumberColumnFilter',
    filterParams: { buttons: ['reset', 'apply'], closeOnApply: true },
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 100,
  },
  // ── Stock % Change Columns ────────────────────────────────
  {
    field: 'yesterdayChangePercent',
    headerName: 'One Day',
    tooltipField: 'yesterdayChangePercent',
    filter: 'agNumberColumnFilter',
    filterParams: { buttons: ['reset', 'apply'], closeOnApply: true },
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 90,
  },
  {
    field: 'oneWeekChangePercent',
    headerName: 'One Week',
    tooltipField: 'oneWeekChangePercent',
    filter: 'agNumberColumnFilter',
    filterParams: { buttons: ['reset', 'apply'], closeOnApply: true },
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 90,
  },
  {
    field: 'oneMonthChangePercent',
    headerName: 'One Month',
    tooltipField: 'oneMonthChangePercent',
    filter: 'agNumberColumnFilter',
    filterParams: { buttons: ['reset', 'apply'], closeOnApply: true },
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 90,
  },
  {
    field: 'threeMonthChangePercent',
    headerName: 'Three Month',
    tooltipField: 'threeMonthChangePercent',
    filter: 'agNumberColumnFilter',
    filterParams: { buttons: ['reset', 'apply'], closeOnApply: true },
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 90,
  },
  {
    field: 'sixMonthChangePercent',
    headerName: 'Six Month',
    tooltipField: 'sixMonthChangePercent',
    filter: 'agNumberColumnFilter',
    filterParams: { buttons: ['reset', 'apply'], closeOnApply: true },
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 90,
  },
  {
    field: 'oneYearChangePercent',
    headerName: 'One Year',
    tooltipField: 'oneYearChangePercent',
    filter: 'agNumberColumnFilter',
    filterParams: { buttons: ['reset', 'apply'], closeOnApply: true },
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 90,
  },
  {
    field: 'twoYearChangePercent',
    headerName: 'Two Year',
    tooltipField: 'twoYearChangePercent',
    filter: 'agNumberColumnFilter',
    filterParams: { buttons: ['reset', 'apply'], closeOnApply: true },
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 90,
  },
  {
    field: 'threeYearChangePercent',
    headerName: 'Three Year',
    tooltipField: 'threeYearChangePercent',
    filter: 'agNumberColumnFilter',
    filterParams: { buttons: ['reset', 'apply'], closeOnApply: true },
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 90,
  },
  {
    field: 'fiveYearChangePercent',
    headerName: 'Five Year',
    tooltipField: 'fiveYearChangePercent',
    filter: 'agNumberColumnFilter',
    filterParams: { buttons: ['reset', 'apply'], closeOnApply: true },
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 90,
  },
  // ── Index % Change Columns ────────────────────────────────
  {
    field: 'indexYesterdayChangePercent',
    headerName: 'Index One Day',
    tooltipField: 'indexYesterdayChangePercent',
    filter: 'agNumberColumnFilter',
    filterParams: { buttons: ['reset', 'apply'], closeOnApply: true },
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 90,
  },
  {
    field: 'indexOneWeekChangePercent',
    headerName: 'Index One Week',
    tooltipField: 'indexOneWeekChangePercent',
    filter: 'agNumberColumnFilter',
    filterParams: { buttons: ['reset', 'apply'], closeOnApply: true },
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 90,
  },
  {
    field: 'indexOneMonthChangePercent',
    headerName: 'Index One Month',
    tooltipField: 'indexOneMonthChangePercent',
    filter: 'agNumberColumnFilter',
    filterParams: { buttons: ['reset', 'apply'], closeOnApply: true },
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 90,
  },
  {
    field: 'indexThreeMonthChangePercent',
    headerName: 'Index Three Month',
    tooltipField: 'indexThreeMonthChangePercent',
    filter: 'agNumberColumnFilter',
    filterParams: { buttons: ['reset', 'apply'], closeOnApply: true },
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 90,
  },
  {
    field: 'indexSixMonthChangePercent',
    headerName: 'Index Six Month',
    tooltipField: 'indexSixMonthChangePercent',
    filter: 'agNumberColumnFilter',
    filterParams: { buttons: ['reset', 'apply'], closeOnApply: true },
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 90,
  },
  {
    field: 'indexOneYearChangePercent',
    headerName: 'Index One Year',
    tooltipField: 'indexOneYearChangePercent',
    filter: 'agNumberColumnFilter',
    filterParams: { buttons: ['reset', 'apply'], closeOnApply: true },
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 90,
  },
  {
    field: 'indexTwoYearChangePercent',
    headerName: 'Index Two Year',
    tooltipField: 'indexTwoYearChangePercent',
    filter: 'agNumberColumnFilter',
    filterParams: { buttons: ['reset', 'apply'], closeOnApply: true },
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 90,
  },
  {
    field: 'indexThreeYearChangePercent',
    headerName: 'Index Three Year',
    tooltipField: 'indexThreeYearChangePercent',
    filter: 'agNumberColumnFilter',
    filterParams: { buttons: ['reset', 'apply'], closeOnApply: true },
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 90,
  },
  {
    field: 'indexFiveYearChangePercent',
    headerName: 'Index Five Year',
    tooltipField: 'indexFiveYearChangePercent',
    filter: 'agNumberColumnFilter',
    filterParams: { buttons: ['reset', 'apply'], closeOnApply: true },
    wrapHeaderText: true,
    autoHeaderHeight: true,
    minWidth: 90,
  },
];

export const YEARWISE_COLUMNS: ColDef[] = COLUMN_DEFS;