export interface MutualFundScheme {
  schemeId: string;
  schemeName: string;
  fundHouse: string;
  fundName: string;
  directFund: string;
  category: string;
  subCategory: string;
  planType: string;
  schemeCode: string;
  schemeType?: string;
  growwVerdictScore?: number | null;
  nav: number | null;
  return1D?: number | null;
  return1Y: number | null;
  return3M: number | null;
  return3Y?: number | null;
  return5Y?: number | null;
  return6M: number | null;
  return7Y?: number | null;
  return10Y?: number | null;
  sipReturn1Y?: number | null;
  sipReturn3Y?: number | null;
  sipReturn5Y?: number | null;
  sipReturn10Y?: number | null;
  docRequired?: boolean;
  minInvestmentAmount?: number | null;
  minSipInvestment?: number | null;
  amc?: string;
  fundManager?: string;
  directSchemeName?: string;
  docType?: string;
  pageView?: number | null;
  subSubCategory?: string;
  tags?: string;
  aum: number | null;
  expenseRatio: string;
  risk: string;
  riskRating: number | null;
  availableForInvestment: boolean;
  sipAllowed: boolean;
  lumpsumAllowed: boolean;
  launchDate: string;
  logoUrl: string;
  exitLoad: string;
  lastUpdatedAt: string;
  assetType?: string;
  companyName?: string;
}
