export interface YearwiseStockSummary {
  symbol: string;
  companyName: string;
  pChange: number;
  open: number;
  dayHigh: number;
  dayLow: number;
  previousClose: number;
  averagePrice: number;
  basePrice: number;
  closePrice: number;
  lastPrice: number;
  issuedSize: number;
  totalTradedVolume: number;
  totalTradedValue: number;
  deliveryToTradedQuantity: number;
  quantityTraded: number;
  deliveryQuantity: number;
  totalMarketCap: number;
  basicIndustry: string;
  isSuspended: string;
  varMargin: string;
  applicableMargin: string;
  adhocMargin: string;
  issueDesc: string | null;
  macro: string;
  sector: string;
  industryInfo: string;
  indexListJson: string;
  tradingSegment: string;
  nameOfComplianceOfficer: string | null;
  yearHighDt: string | null;
  yearLowDt: string | null;
  yearHigh: number;
  yearLow: number;
  cmDailyVolatility: string | null;
  cmAnnualVolatility: string | null;
  yesterdayChangePercent: number;
  oneWeekChangePercent: number;
  oneMonthChangePercent: number;
  threeMonthChangePercent: number;
  sixMonthChangePercent: number;
  oneYearChangePercent: number;
  twoYearChangePercent: number;
  threeYearChangePercent: number;
  fiveYearChangePercent: number;
  oneWeekDate: string | null;
  indexYesterdayChangePercent: number;
  indexOneWeekChangePercent: number;
  indexOneMonthChangePercent: number;
  indexThreeMonthChangePercent: number;
  indexSixMonthChangePercent: number;
  indexOneYearChangePercent: number;
  indexTwoYearChangePercent: number;
  indexThreeYearChangePercent: number;
  indexFiveYearChangePercent: number;
  indexOneWeekDate: string | null;
  indexName: string;
}
