export interface YearwiseStockSummary {
  symbol: string;
  companyName: string;
  sector: string;
  industryInfo: string;
  basicIndustry: string;
  totalTradedVolume: number;
  totalTradedValue: number;
  deliveryToTradedQuantity: number;
  quantityTraded: number;
  deliveryQuantity: number;
  totalMarketCap: number;
  tApplicableMargin: number;
  sDeliveryQuantity: number;
  varMargin: number;
  sApplicableMargin: number;
  adhocMargin: number;
  issueDesc: string;
  macro: string;
  indexListJson: string;
  tradingSegment: string;
  nameOfComplianceOfficer: string;
  yearHighDt: string | null;
  yearLowDt: string | null;
  yearHigh: number;
  yearLow: number;
  yesterdayChangePercent: number;
  oneWeekChangePercent: number;
  oneMonthChangePercent: number;
  threeMonthChangePercent: number;
  sixMonthChangePercent: number;
  oneYearChangePercent: number;
  twoYearChangePercent: number;
  threeYearChangePercent: number;
  fiveYearChangePercent: number;
  oneWeekDate: string | null;
  indexYesterdayChangePercent: number;
  indexOneWeekChangePercent: number;
  indexOneMonthChangePercent: number;
  indexThreeMonthChangePercent: number;
  indexSixMonthChangePercent: number;
  indexOneYearChangePercent: number;
  indexTwoYearChangePercent: number;
  indexThreeYearChangePercent: number;
  indexFiveYearChangePercent: number;
  indexOneWeekDate: string | null;
  indexName: string;
}
