CREATE  OR ALTER  VIEW [dbo].[vw_YearwiseStockSummary] AS
SELECT 
    T.TotalTradedVolume,
    T.TotalTradedValue,
    T.DeliveryToTradedQuantity,
    T.ApplicableMargin      AS T_ApplicableMargin,
    T.QuantityTraded,
    T.DeliveryQuantity      AS DeliveryQuantity,
    T.TotalMarketCap,
    S.BasicIndustry,
    S.IsSuspended,
    S.DeliveryQuantity      AS S_DeliveryQuantity,
    S.VarMargin,
    S.ApplicableMargin      AS S_ApplicableMargin,
    S.AdhocMargin,
    S.IssueDesc,
    S.Macro,
    S.Sector,
    S.IndustryInfo,
    S.IndexListJson,
    S.TradingSegment,
    S.NameOfComplianceOfficer,
    P.YearHighDt,
    P.YearLowDt,
    P.YearHigh,
    P.YearLow,
    M.CompanyName,
    M.Symbol,
    Y.YesterdayChangePercent,
    Y.OneWeekChangePercent,
    Y.OneMonthChangePercent,
    Y.ThreeMonthChangePercent,
    Y.SixMonthChangePercent,
    Y.OneYearChangePercent,
    Y.TwoYearChangePercent,
    Y.ThreeYearChangePercent,
    Y.FiveYearChangePercent,
    Y.OneWeekDate,
    Y.IndexYesterdayChangePercent,
    Y.IndexOneWeekChangePercent,
    Y.IndexOneMonthChangePercent,
    Y.IndexThreeMonthChangePercent,
    Y.IndexSixMonthChangePercent,
    Y.IndexOneYearChangePercent,
    Y.IndexTwoYearChangePercent,
    Y.IndexThreeYearChangePercent,
    Y.IndexFiveYearChangePercent,
    Y.IndexOneWeekDate,
    Y.IndexName
FROM YearwiseDataEntities Y
INNER JOIN TradeInfoEntities T ON REPLACE(Y.Symbol, 'EQN', '') = T.Symbol
INNER JOIN SecInfoEntities  S ON S.Symbol = T.Symbol
INNER JOIN PriceInfoEntities P ON S.Symbol = P.Symbol
INNER JOIN MetaDataEntities  M ON M.Symbol = P.Symbol;
GO