CREATE  OR ALTER  VIEW [dbo].[vw_YearwiseStockSummary] AS
SELECT 
    Y.YesterdayChangePercent,
    Y.OneWeekChangePercent,
    Y.OneMonthChangePercent,
    Y.ThreeMonthChangePercent,
    Y.SixMonthChangePercent,
    Y.OneYearChangePercent,
    Y.TwoYearChangePercent,
    Y.ThreeYearChangePercent,
    Y.FiveYearChangePercent,
    Y.OneWeekDate,
    Y.IndexYesterdayChangePercent,
    Y.IndexOneWeekChangePercent,
    Y.IndexOneMonthChangePercent,
    Y.IndexThreeMonthChangePercent,
    Y.IndexSixMonthChangePercent,
    Y.IndexOneYearChangePercent,
    Y.IndexTwoYearChangePercent,
    Y.IndexThreeYearChangePercent,
    Y.IndexFiveYearChangePercent,
    Y.IndexOneWeekDate,
    Y.IndexName,
    T.TotalTradedVolume,
    T.TotalTradedValue,
    T.DeliveryToTradedQuantity,
    T.QuantityTraded,
    T.DeliveryQuantity,
    T.TotalMarketCap,
    T.LastPrice,
    T.IssuedSize,
    S.BasicIndustry,
    S.IsSuspended,
    S.VarMargin,
    S.ApplicableMargin,
    S.AdhocMargin,
    S.Macro,
    S.Sector,
    S.IndustryInfo,
    S.TradingSegment,
    S.NameOfComplianceOfficer,
    P.YearHighDt,
    P.YearLowDt,
    P.YearHigh,
    P.YearLow,
    P.CmDailyVolatility,
    P.CmAnnualVolatility,
    M.CompanyName,
    M.Symbol,
    M.PChange,
    M.[Open],
    M.DayHigh,
    M.DayLow,
    M.PreviousClose,
    M.AveragePrice,
    M.BasePrice,
    M.ClosePrice
FROM YearwiseDataEntities    Y
INNER JOIN TradeInfoEntities T ON REPLACE(Y.Symbol, 'EQN', '') = T.Symbol
INNER JOIN SecInfoEntities   S ON S.Symbol = T.Symbol
INNER JOIN PriceInfoEntities P ON S.Symbol = P.Symbol
INNER JOIN MetaDataEntities  M ON M.Symbol = P.Symbol;
GO